# Basic Numpy

In [4]:
# Create 2 new lists height and weight
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# Import the numpy package as np
import numpy as np

# Create 2 numpy arrays from height and weight
np_height = np.array(height)
np_weight = np.array(weight)

print(np_height)
print(type(np_height))

[1.87, 1.87, 1.82, 1.91, 1.9, 1.85]
[1.87 1.87 1.82 1.91 1.9  1.85]
<class 'numpy.ndarray'>


In [8]:
# Calculate bmi
bmi = np_weight / (np_height ** 2)

# Print the result
print(bmi)

[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]


In [11]:
# Print only those observations above 27
bmi[bmi > 27]

array([27.88755755, 28.75558507])