---
# Accessing Single Element

In [2]:
import numpy as np

my_array = np.array([0, 111, 222, 333, 444])
print(my_array)
my_array[0] = 111
print(my_array)

[1 2 3 4 5]
[111   2   3   4   5]


---
# View Multiple Element

In [13]:
# start:end:step
my_array = np.array([0, 111, 222, 333, 444])
print(my_array[0:5:2])

# start:end:
my_array = np.array([0, 111, 222, 333, 444])
print(my_array[0:2:])

# ::step
my_array = np.array([0, 111, 222, 333, 444])
print(my_array[::3])

[  0 222 444]
[  0 111]
[  0 333]
