In [27]:
import torch

---
# torch.tensor()

In [28]:
result = torch.tensor([1, 2, 3])
print(result)

result = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(result)

tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


---
# torch.randint()

Returns a tensor filled with random integers generated uniformly between low (inclusive) and high (exclusive).

The shape of the tensor is defined by the variable argument size.

In [52]:
min = -100
max = 100
size = (5,)
result = torch.randint(min, max, size)
print(result)

size = (5, 2)
result = torch.randint(min, max, size)
print(result)

tensor([-22, -30,  30,  -6,  16])
tensor([[-29, -56],
        [ 33,  53],
        [  1,  33],
        [-94,  46],
        [ 76, -41]])


---
# torch.zeros()

In [33]:
result = torch.zeros(2, 3)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


---
# torch.ones()

In [34]:
result = torch.ones(3, 6)
print(result)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


---
# torch.empty()

Returns a tensor filled with uninitialized data.

In [35]:
result = torch.empty(2, 4)
print(result)

tensor([[-6.7085e+04,  9.0384e-43,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


---
# torch.range()

This function is deprecated and will be removed in a future release because its behavior is inconsistent with Python’s range builtin. Instead, use torch.arange(), which produces values in [start, end).

In [38]:
start = -100
end = 100
step = 50.5 
result = torch.range(start, end, step)
print(result)

tensor([-100.0000,  -49.5000,    1.0000,   51.5000])


C:\Users\anton\AppData\Local\Temp\ipykernel_4712\4147762641.py:4: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  result = torch.range(start, end, step)


---
# torch.arange()

In [40]:
start = -5
end = 5
result = torch.arange(start, end)
print(result)

tensor([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])


---
# torch.linspace()

In [50]:
start = -5
end = 5
steps = 5
result = torch.linspace(start, end, steps=steps)
print(result)

tensor([-5.0000, -2.5000,  0.0000,  2.5000,  5.0000])


---
# torch.logspace()

In [51]:
start = -5
end = 5
steps = 5
result = torch.logspace(start, end, steps=steps)
print(result)

tensor([1.0000e-05, 3.1623e-03, 1.0000e+00, 3.1623e+02, 1.0000e+05])


---
# torch.eye()
Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.

In [58]:
result = torch.eye(4)
print(result)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
