In [48]:
import torch

---
# torch.cat()

In [49]:
tensor1 = torch.tensor([1,2,3,4])
tensor2 = torch.tensor([100, 200])
tensor = torch.cat((tensor1, tensor2), dim=0)
tensor

tensor([  1,   2,   3,   4, 100, 200])

---
# torch.tril()
Returns the lower triangular part of the matrix (2-D tensor) or batch of matrices input, the other elements of the result tensor out are set to 0.

In [50]:
my_tensor = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(f"Before\n{my_tensor}\n")

my_tensor = torch.tril(my_tensor)
print(f"After\n{my_tensor}\n")

Before
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

After
tensor([[ 1,  0,  0],
        [ 4,  5,  0],
        [ 7,  8,  9],
        [10, 11, 12]])



---
# torch.triu()
Returns the upper triangular part of a matrix (2-D tensor) or batch of matrices input, the other elements of the result tensor out are set to 0.

In [51]:
my_tensor = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(f"Before\n{my_tensor}\n")

my_tensor = torch.triu(my_tensor)
print(f"After\n{my_tensor}\n")

Before
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

After
tensor([[1, 2, 3],
        [0, 5, 6],
        [0, 0, 9],
        [0, 0, 0]])



---
# torch.multinomial()
Returns a tensor where each row contains num_samples indices sampled from the multinomial (a stricter definition would be multivariate, refer to torch.distributions.multinomial.Multinomial for more details) probability distribution located in the corresponding row of tensor input.

In [52]:
probalities = torch.tensor([0.1, 0.9])
my_tensor = torch.multinomial(probalities, num_samples=5, replacement=True)
print(my_tensor)

tensor([1, 1, 1, 0, 1])


---
# torch.masked_fill()

In [53]:
my_tensor = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
print(my_tensor)

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])


In [54]:
my_tensor = torch.exp(my_tensor)
print(my_tensor)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


---
# torch.transpose()

In [55]:
my_tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(f"Initial\n{my_tensor}\n")
my_tensor = torch.transpose(my_tensor, 0, 1)
print(f"After transpose\n{my_tensor}\n")

Initial
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

After transpose
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])



---
# torch.stack()

In [56]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])
my_tensor = torch.stack([tensor1, tensor2, tensor3])
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


---