In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F

---
# Dot Product (@) and torch.matmul()

In [5]:
# (1x3) . (3x1) = (1x1)
matrix1 = torch.tensor([1,2,3])     # 1x3
matrix2 = torch.tensor([[4],
                        [5],
                        [6]])       # 3x1
matrix3 = matrix1 @ matrix2         # dot product (1x1)
print(matrix3)
print(torch.matmul(matrix1, matrix2))
print()

# (1x3) . (3x2) = (1x2)
matrix1 = torch.tensor([1,2,3])     # 1x3
matrix2 = torch.tensor([[4,5],
                        [6,7],
                        [8,9]])     # 3x2
matrix3 = matrix1 @ matrix2         # dot product (1x2)
print(matrix3)
print(torch.matmul(matrix1, matrix2))
print()


# (2x3) . (3x2) = (2x2)
matrix1 = torch.tensor([[1,2,3],
                        [4,5,6]])   # 2x3
matrix2 = torch.tensor([[10,20],
                        [30,40],
                        [50,60]])   # 3x2
matrix3 = matrix1 @ matrix2         # dot product (2x2)
print(matrix3)
print(torch.matmul(matrix1, matrix2))
print()


tensor([32])
tensor([32])

tensor([40, 46])
tensor([40, 46])

tensor([[220, 280],
        [490, 640]])
tensor([[220, 280],
        [490, 640]])



---
# torch.softmax()
Softmax(xi​)=∑j​exp(xj​)exp(xi​)​


In [12]:
my_tensor = torch.tensor([1.,2.,3.])
print(F.softmax(my_tensor, dim=0))

tensor([0.0900, 0.2447, 0.6652])
