---
# np.array()

In [44]:
import numpy as np

# 1 Dimension
my_array = np.array([111, 222, 333, 444, 555])
print(my_array)
print(type(my_array))
print()

# 2 Dimension
my_array = np.array([[111, 222, 333, 444, 555], [666, 777, 888, 999, 000]])
print(my_array)
print()

# 3 Dimension
my_array = np.array([[[111, 222, 333, 444, 555], [666, 777, 888, 999, 000]], 
                     [[1, 2, 3, 4, 5],[6, 7, 8, 9, 0]]])
print(my_array)


[111 222 333 444 555]
<class 'numpy.ndarray'>

[[111 222 333 444 555]
 [666 777 888 999   0]]

[[[111 222 333 444 555]
  [666 777 888 999   0]]

 [[  1   2   3   4   5]
  [  6   7   8   9   0]]]


---
# np.zeros()

In [3]:
my_array = np.zeros(5)
print(my_array)

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


---
# np.one()

In [14]:
my_array = np.ones(5)
print(my_array)

[1. 1. 1. 1. 1.]


---
# np.empty()
The function empty creates an array whose initial content is random and depends on the state of the memory.

The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [13]:
my_array = np.empty(10)
print(my_array)

[ 56.02222222  98.02222222 140.02222222 182.02222222 224.02222222
 266.02222222 308.02222222 350.02222222 392.02222222 403.32222222]


---
# np.arange()

In [17]:
# Start from 0 to less than 5 with step 1
my_array = np.arange(5)
print(my_array)

# Start from 10 to less than 50 with step 5
my_array = np.arange(10, 50, 5)
print(my_array)

[0 1 2 3 4]
[10 15 20 25 30 35 40 45]


---
# np.linspace()
You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:

In [21]:
my_array = np.linspace(1, 10, num=5)
print(my_array)

my_array = np.linspace(1, 10, num=10)
print(my_array)


[ 1.    3.25  5.5   7.75 10.  ]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


---
# Specifying your data type
While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword.

In [35]:
my_array = np.zeros(15, dtype=np.int64)
print(my_array)
print(type(my_array[0]))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
<class 'numpy.int64'>
