---
# ndim, shape, size, dtype

- **ndarray.ndim** will tell you the number of axes, or dimensions, of the array.
- **ndarray.size** will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.
- **ndarray.shape** will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [13]:
import numpy as np

def array_info(array):
    print(array)
    print("Dimension: " + str(array.ndim))
    print("Shape: " + str(array.shape))
    print("Size: " + str(array.size))
    print("dtype: " + str(array.dtype))
    print()

my_array = np.array([1, 2, 3, 4, 5])
array_info(my_array)

my_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
array_info(my_array)

my_array = np.array([[[[[[[[1.1, 2.2, 3.3, 4.4, 5.5]]]]]]]])
array_info(my_array)

[1 2 3 4 5]
Dimension: 1
Shape: (5,)
Size: 5
dtype: int32

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Dimension: 2
Shape: (2, 5)
Size: 10
dtype: int32

[[[[[[[[1.1 2.2 3.3 4.4 5.5]]]]]]]]
Dimension: 8
Shape: (1, 1, 1, 1, 1, 1, 1, 5)
Size: 5
dtype: float64

