---
# Sort

In [ ]:
import numpy as np
my_array = np.array([999, 200, 300, 100, 500])
print(my_array)
print(np.sort(my_array))

---
# Concatenate

In [9]:
my_list1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
my_list2 = np.array([[111, 222, 333]])
print(np.concatenate((my_list1, my_list2)))

[[  1   2   3]
 [  4   5   6]
 [  7   8   9]
 [111 222 333]]
