---
# Reshape

In [5]:
import numpy as np

my_list = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
print("Initial array:\n" + str(my_list))

my_list = my_list.reshape(3, 5)
print("\nReshape array:\n" + str(my_list))

Initial array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Reshape array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
